apiVersion: v1
kind: Service
metadata:
  name: service-wso2am
  namespace: test-env
  labels:
    app: wso-api-manager
  annotations:
    environment: Test
    owner: pokatilov-ov
    project: WSO2-K8s-Project
spec:
  # sessionAffinity: ClientIP
  selector:
    app: wso-api-manager
  ports:
    - name: ui
      protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 30002
    - name: port-1
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: port-2
      protocol: TCP
      port: 8243
      targetPort: 8243
    - name: port-3
      protocol: TCP
      port: 8280
      targetPort: 8280
    - name: port-4
      protocol: TCP
      port: 9099
      targetPort: 9099
    - name: port-5
      protocol: TCP
      port: 9611
      targetPort: 9611
    - name: port-6
      protocol: TCP
      port: 9711
      targetPort: 9711
    - name: port-7
      protocol: TCP
      port: 9763
      targetPort: 9763
    - name: port-8
      protocol: TCP
      port: 9999
      targetPort: 9999
    - name: port-9
      protocol: TCP
      port: 11111
      targetPort: 11111
  type: NodePort
