all:
  children:
    master:
      hosts:
        master-1:
          ansible_host: 10.255.132.16
          ansible_user: k8s-user

    workers:
      hosts:
        worker-3:
          ansible_host: 10.255.132.15
          ansible_user: k8s-user
        worker-2:
          ansible_host: 10.255.132.14
          ansible_user: k8s-user
        worker-1:
          ansible_host: 10.255.132.13
          ansible_user: k8s-user
        worker-0:
          ansible_host: 10.255.132.12
          ansible_user: k8s-user

  vars:
    ansible_python_interpreter: /usr/bin/python3
