apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-wso2eii
  namespace: test-env
  labels:
    app: wso-ei-integrator
  annotations:
    environment: Test
    owner: pokatilov-ov
    project: WSO2-K8s-Project
spec:
  # replicas: 3
  # minReadySeconds: 150
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0
  #   type: RollingUpdate
  selector:
    matchLabels:
      app: wso-ei-integrator
  template:
    metadata:
      labels:
        app: wso-ei-integrator
    spec:
      containers:
        - name: wso2eii
          image: wso2/wso2ei-integrator:6.6.0-centos7
          ports:
            - containerPort: 9443
            - containerPort: 8280
            - containerPort: 8243
            - containerPort: 4100
          resources:
            requests:
              cpu: 2
              memory: 2000M
            limits:
              cpu: 2
              memory: 3000M
