apiVersion: v1
kind: Service
metadata:
  name: service-wso2eii
  namespace: test-env
  labels:
    app: wso-ei-integrator
  annotations:
    environment: Test
    owner: pokatilov-ov
    project: WSO2-K8s-Project
spec:
  selector:
    app: wso-ei-integrator
  ports:
    - name: ui
      protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 30001
    - name: port-1
      protocol: TCP
      port: 8280
      targetPort: 8280
    - name: port-2
      protocol: TCP
      port: 8243
      targetPort: 8243
    - name: port-3
      protocol: TCP
      port: 4100
      targetPort: 4100
  type: NodePort
